package org.example.robobob.service.processor;

/**
 * Interface representing a processor for handling specific types of questions.
 * Implementations of this interface should define the logic for determining
 * whether they can process a given question and how to process it.
 */
public interface QuestionProcessor {

    /**
     * Determines if this processor can handle the given question.
     *
     * @param question the question to evaluate
     * @return true if this processor can handle the question, false otherwise
     */
    boolean canProcess(String question);

    /**
     * Processes the given question and returns a response.
     *
     * @param question the question to process
     * @return the response generated by processing the question
     */
    String process(String question);
}